services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /mnt/hd480/emby/config:/config # Configuration directory
      - /mnt/hd480/emby/series:/mnt/series # Media directory
      - /mnt/hd480/emby/filmes:/mnt/filmes # Media directory
    ports:
      - 80:8096 # HTTP port
      - 443:8920 # HTTPS port
    restart: on-failure