services:
 minio:
   container_name: minio
   image: quay.io/minio/minio
   ports:
           - 9000:9000
           - 9001:9001
   volumes:
##           mkdir -p /opt/docker/minio/{data,certs}
##           chmod -r 777 /opt/docker/minio
##           DOMAIN=dominio.com.br
##           ln -s /etc/letsencrypt/live/$DOMAIN/privkey.pem private.key
##           ln -s /etc/letsencrypt/live/$DOMAIN/fullchain.pem public.crt
           - /etc/letsencrypt:/etc/letsencrypt
           - /opt/docker/minio/data:/data
           - /opt/docker/minio/certs/:/root/.minio/certs
   environment:
           - MINIO_ROOT_USER=root
           - MINIO_ROOT_PASSWORD=mudar123456
   entrypoint: minio
   command: server /data --console-address ":9001"
#    networks:
#        siga:
# 
