services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    volumes:
      - /:/srv #Arquivos
      - /mnt/filebrowser/:/config/
      - /mnt/filebrowser/:/database/
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "81:80"
    restart: unless-stopped

